### ISSUE TITLE
Add button to hide/show the ribbon like the one on Windows Explorer

### ISSUE THREAD

**Issue by skysurfer1** [DougHennig/Ribbon#11]
I'd like you to add a small button so that when clicked it hides the ribbon, except the main options, and when clicked again, the ribbon shows.

This would be useful when there are forms that have much information to be shown, this button would allow to leave more space for those forms (when the ribbon is hidden).

**Comment by DougHennig** [comment]
How will the other controls on the form know they are supposed to move up when the ribbon is hidden?

**Comment by DougHennig** [comment]
Thanks for the suggestion. I am working on it. I don't have a timeframe for completion because it's a lot more complicated than it seems.

**Comment by DougHennig** [comment]
The latest version has this new feature. See README for details.

**Comment by skysurfer1** [comment]
> The latest version has this new feature. See README for details.

That's good news! Thank you very much. I'll take a look at it.
