### ISSUE TITLE
Make Method sfRibbonBase.GetThemeColor Public (not protected)

### ISSUE THREAD

**Issue by VfpImaging** [DougHennig/Ribbon#14]
## 📝 It would be interesting to let the method "GetThemeColor" public,to allow an easier access to the themes used. For instance, to make other objects outside the Ribbon to use some of the Themed colors.

lnHighlightedColor = Thisform.oRibbon.GetThemeColor('buttonhighlightcolor')

Doug, This is an amazing work!
Loving to play with it, thanks for sharing!

**Comment by LOGOmichael** [comment]
That's a great idea of Cesar which i would love alot.

One could even add more / other items to the XML and use is for own purposes. 💯

**Comment by VfpImaging** [comment]
Yes, IMHO, it would be perfect if the "oRibbon" main object had some Specific properties available after the theme was selected, something like:
? Thisform.oRIbbon.nButtonHighlightColor
Or maybe having a new "EMPTY" object something like "oCurrentTheme" with such properties, like:
? Thisform.oRibbon.oCurrentTheme.nButtonHighlightColor

It would be interesting to have these colors easily exposed because they would drive other Form object colors.
On my side, I just turned "GetThemeColor" to public and my problem is solved.

**Comment by DougHennig** [comment]
Done in the latest build. Thanks for the suggestion.
