### ISSUE TITLE
sfribbonmenuform should have ShowInTaskBar = .F.

### ISSUE THREAD

**Issue by LOGOmichael** [DougHennig/Ribbon#15]
### What's going on?

If a menu is instantiated, the form/window of the different menu-levels show up on the windows taskbar.

### ✔️ Expected result / Actual Result

The windows used by the menusystem should not show up on the taskbar. The forms are only cleverly used by the menu-object-hierachy and are not "real" windows to be presented to the user on the taskbar. 

...especially not because their title-caption is "sffibbonmenu" 😄 

### Special Hint
This bug might be only true if used in a top-level-form or the _screen itself. I have not tested to the contrary as my project resides directly IN _SCREEN which works great with just two little glitches. This being on of them.

### Solution
Easy: Set **sfribbonmenuform.ShowInTaskbar=.F.** and everyone will be happy

## 📷 Screenshots

![image](https://github.com/DougHennig/Ribbon/assets/94449050/f84b48c7-efd2-483d-9d49-8a59e125ad6f)

![image](https://github.com/DougHennig/Ribbon/assets/94449050/77697205-d693-4187-bab0-7264e019b837)

**Comment by VfpImaging** [comment]
Perfect, I can confirm that!

**Comment by DougHennig** [comment]
Fixed in the latest build.
