### ISSUE TITLE
Menu on sfribbonToolbarMenu has top-offset when used in _SCREEN

### ISSUE THREAD

**Issue by LOGOmichael** [DougHennig/Ribbon#16]
### What's going on?
When sfRibbon is used directly on _SCREEN, a menu attached to a sfRibbonToolbarButton has an offset to its top-property which should not be there.

The code shows why this happens. 😉 

**This only happens when oRibbon is attached directly to _SCREEN**
...which works perfectly well.

### ✔️ Expected result
The menu should be "attached" to the ribbon as it is when used on a "normal" form.

### Solution

The Code of **sfRibbonToolbarButton.ShowMenu** is correctly using a special treatment if used on a "desktop=.T."-form. **But...** if used in _SCREEN the following code does not break, but delivers the wrong assumption as _SCREEN.Desktop is READONLY and cannot be altered to a usable .T.

Original Code
`dodefault(objtoclient(This, 1) + This.Height + Thisform.Top + ;
		sysmetric(9) + sysmetric(4) + ;
		iif(Thisform.Desktop, 0, sysmetric(9) + sysmetric(20)), ;
	objtoclient(This, 2) + Thisform.Left + sysmetric(3))
`

If added an additional OR to test for _SCREEN, everything works fine:

`dodefault(objtoclient(This, 1) + This.Height + Thisform.Top + ;
		sysmetric(9) + sysmetric(4) + ;
		iif(Thisform.Desktop OR thisform.HWnd==_screen.HWnd, 0, sysmetric(9) + sysmetric(20)), ;
	objtoclient(This, 2) + Thisform.Left + sysmetric(3))
`

## 📷 Screenshots

![image](https://github.com/DougHennig/Ribbon/assets/94449050/057cc612-7be8-4973-9d18-4294ea6d4ce2)

![image](https://github.com/DougHennig/Ribbon/assets/94449050/c02535c6-0aeb-4261-b864-1bde52a91789)

**Comment by DougHennig** [comment]
Fixed in the latest build.
