### ISSUE TITLE
RibbonDisplayButton - Menu shows on wrong position

### ISSUE THREAD

**Issue by LOGOmichael** [DougHennig/Ribbon#19]
## 📝 What's going on?

The menu activated on click to the oRibbon.RibbonDisplayButton is show on a wonky position. ...at least when the Ribbon is used in _SCREEN. 

As the sfribbonmenu-form is a Top-Level-Form, the menuform.left is always absolut to windows-screen-positions not to THISFORM-relative-position.

### ✔️ Expected result

As with the usage of menus on sfribbonToobarButton the menu should show up right "under" the button/ribbon and not "somewhere"-else.  

### ❌ Actual result

![image](https://github.com/DougHennig/Ribbon/assets/94449050/91aea690-2308-4c91-981b-a14a0d4f406d)

The position of the menu is dependent of windows-screensize, mainform-size and -postiion. Which should not be the case.

Digging to the code, i see a difference in calling the .ShowMenu() Function between the call used in sfRibbonToolbarButton (works good) and the call used on the RibbonDisplayButton

## Solutions so far

There seems to be a double-headed but in here.

sfRibbonToobarButton has special Code in its ShowMenu - Method. The ShowMenu-Call from the RibbonDisplayButton has no special treatment for positions in it. It is simply called as-is.

If i copy the code to the RibbonDisplayButton.ShowMenu, everything works (nearly)

![image](https://github.com/DougHennig/Ribbon/assets/94449050/172bb489-7a28-40a8-8658-f7e17d94b584)

But this is counteracted by a code specially built-in for "off-form"-positions to achieve menu-positions not expand over the right border of the form.

![image](https://github.com/DougHennig/Ribbon/assets/94449050/5f66cb96-739d-484e-8650-6c59e4274d23)

As sfribbonmenuform is a top-Level-form, its .LEFT is always relative to windows-screen and not THISFORM.LEFT.

My solution works for _SCREEN & DESKTOP=.T. usage, but i have not tested sideeffects to "regular" form usage. It is possible that there needs to be a different aproach for each scenario.

Some tweaking is needed for the top-position on the Ribbon-Button.ShowMenu-Call, but that's something for another day.

**Comment by DougHennig** [comment]
Fixed in the latest build: sort of. The menu is now positioned correctly but the timer is still closing it immediately after it appears when the ribbon is in _SCREEN (issue #17).
