### ISSUE TITLE
Suggestion: New Property for "SfRibbonToolbarButton" - "ClickEvent"

### ISSUE THREAD

**Issue by VfpImaging** [DougHennig/Ribbon#21]
## 📝 Use event binding to associate a form method to each button click event

Instead of using sometimes dangerous Execscript, I would add a new property to the Toolbar buttons - something like "ClickEvent". This would store the Current form related Method that would be fired when the button was clicked.
Internally, something similar to below would happen, at the button initialization:

```
IF NOT EMPTY(This.ClickEvent) and PEMSTATUS(Thisform, This.ClickEvent, 5) && We have the method in the form
   BINDEVENT(This, "Click", Thisform, This.ClickEvent)
ENDIF
```

This would provide another safe way for us to put whatever code we like.
In my case, the Ribbon was not being released because the object "loThisform" was still active. This used to happen when an external object was calling the Form.Release().

If you agree to that, the current Click event should not show the "Not Implemented" Messagebox when empty

On my side, I am currently using the way below using BINDEVENTS directly with nice results:

```
m.loButton = .AddButton()
WITH m.loButton
	* .IMAGE   = m.lcImagePath + "Exit.png"
	.CAPTION = "Close"
	.COMMAND = "SET REPORTBEHAVIOR 90" && Dummy command to avoid the "Not implemented" msg
ENDWITH
BINDEVENT(loButton, "Click", Thisform, "ActionClose")

```

**Comment by DougHennig** [comment]
Thanks for the suggestion. I implemented it slightly differently in the latest release: I added an OnClick method to the button class and made the Click event use RAISEEVENT to raise it as an event. So, you would use this instead:

BINDEVENT(loButton, 'OnClick', Thisform, 'ActionClose')

**Comment by VfpImaging** [comment]
Sounds perfect, thanks!
