### ISSUE TITLE
public loThisform

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/Ribbon#4]
rather than use a public variable i have added (my copy) an  .oParentform property to sfribbonbase and sfribbonmenuform , set it to 'thisform' in their .init() events and then changed sfribbontoolbarbutton.click() to 
			loThisform = This.oparentform

n

**Comment by DougHennig** [comment]
The problem with that approach is that the form contains a reference to the ribbon and the ribbon contains a reference to the form, which can make for zombie forms (they appear to close but aren't actually released) unless you're very careful about cleaning up the object references.
