### ISSUE TITLE
ribbon overflow

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/Ribbon#6]
Doug,

i've added (my copy) a simple mechanism that shows a double chevron top right if the active toolbar's controls overflow the width of the form..... click and it will shuffle the toolbar left so all the remaining buttons are visible.
See photos
![over1](https://user-images.githubusercontent.com/87875272/130160397-c6c54e74-0147-4cf5-bb0e-bca7028fafcb.JPG)
![over2](https://user-images.githubusercontent.com/87875272/130160396-04243ab6-4cf4-4dd9-a8d3-bc2fbacc38e5.JPG)
![over3](https://user-images.githubusercontent.com/87875272/130160393-2322d34b-434e-4a2f-9994-dcfc1ab63214.JPG)

is this something you would want to include?

n

**Comment by DougHennig** [comment]
Wouldn't it be better to have more tabs than to have to scroll the toolbar?

But, sure, show me the code. No harm adding it.

**Comment by NigelGomm** [comment]
trouble is i have no idea of the PCs this will be running on and some customers may have small monitors and/or resize the app;  just don't want functionality disappearing over the edge of the form. 
MS Outlook resizes itself and drops buttons or makes them horizontal... earlier versions IIRC added a 'More' button with the missing functionality in a menu. This was easier!

n
[sfribbon .zip](https://github.com/DougHennig/Ribbon/files/7024002/sfribbon.zip)

**Comment by NigelGomm** [comment]
minor change. moved the call on lbloverflow.refresh() from sfribbon.sfribbon.selecttab() to sfribbontab.selected_assign

[sfribbon.zip](https://github.com/DougHennig/Ribbon/files/7027504/sfribbon.zip)

**Comment by NigelGomm** [comment]
my aplologies. not related to the ribbon overflow but i had broken the public lothisform -> .oparentform thing in that version.

[sfribbon.zip](https://github.com/DougHennig/Ribbon/files/7032701/sfribbon.zip)

**Comment by DougHennig** [comment]
Because these changes don't really work like an Office ribbon, I'm not going to add them to the project. Perhaps you could create a GitHub repository for your customized version if anyone else is interested in it.
