### ISSUE TITLE
tabs remaining highlighted

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/Ribbon#7]
Doug,
if you press mousedown on a tab and then move the mouse up to the window's title bar before releasing... the tab doesn't get a .mouseleave() event and remains highlighted. (i must have been doing this inadvertently every once in a while when clicking on a tab).
This is compounded by the line in .mouseenter()
This.nBackColor      = This.BackColor
saving the (now) highlighted colour; themes_assign will have set .nBackColor already so i have commented this line out. Now at least next time i .mouseleave() it gets reset to the correct .backcolor.

I'm guessing the only way to prevent this happening in the first place is to put the tab's .top to 1 so it gets a chance to see .mouseleave() ?

n

**Comment by DougHennig** [comment]
Moving over the button again clears the highlight, so I don't think this is too big of an issue,
